version: 0.2

# References
# https://stackoverflow.com/questions/47657423/get-github-git-branch-for-aws-codebuild

phases:
  install:
    commands:
      - npm install npm -g
      - npm config set audit false
      - npm install

  build:
    commands:
      - ./.codebuild/gitTags.sh
      - npm run travis-ci

